name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Добавляем возможность ручного запуска

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers with screenshots
        run: npx playwright install --with-deps -screenshot

      - name: Run Playwright tests with screenshots
        run: npx playwright test --project=chromium --screenshot

      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: playwright-report

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with: 
          name: playwright-screenshots
          path: playwright-screenshot
